### ISSUE TITLE
Opinions on linter and formatter

### ISSUE THREAD

**Issue by w00kie** [Stellar-Quest-Lumenauts/fantastic-goggles#19]
So we started that discussion a bit on the discord sometime ago but did not come to any conclusion, but we should really agree on a linter options and auto-formatters for everyone to follow or force on commits with github actions.

I like `black` to auto-format and `flake8` for linting. It helps to catch a lot of issues early.

`black` can be a bit harsh at first as it's really all or nothing but that's the point in python: there should only be one correct way to do things.

![This is the way](https://media.giphy.com/media/1hAxQTH0HEWS3L0oRF/giphy.gif)

**Comment by MatejMecka** [comment]
I'm personally ok with using both, the only thing that would be nice is if the line limit can be extended to 120 characthers

**Comment by w00kie** [comment]
We can sent the `max-line-length` in `black` and `flake8` to 119 which is the recommended length in Django and the default size of Github's own editor.

**Comment by Smephite** [comment]
See #24
