### ISSUE TITLE
Distribution function - must it be async?

### ISSUE THREAD

**Issue by w00kie** [Stellar-Quest-Lumenauts/fantastic-goggles#21]
I'm writing a bunch of unit tests and trying to do as much stuff that is not discord related as I don't have a good mocker for discord functionality. A good thing to test would be this distribution function and looking at it I don't see a good reason for it to be async as it does not call any discord stuff inside. 

https://github.com/Stellar-Quest-Lumenauts/fantastic-goggles/blob/431e64404cb6e113e9e6e9e9a27b10e6b60b263f/helpers/discord.py#L40-L88

Can we make it synchronous so it's simpler to unit test? @Smephite, I think that was your code originally?

**Comment by Smephite** [comment]
I agree with you. I don't see why this shouldn't be sync

**Comment by w00kie** [comment]
I made it sync and refactored it just a little bit to make it easier to test in #25
